# Generated by Django 4.1.1 on 2022-10-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagen',
            field=models.ImageField(default='null', upload_to='pokemons', verbose_name='Imagen'),
        ),
    ]
