# Generated by Django 4.1.1 on 2022-10-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianza', '0002_pokemon_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataque',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
