# Generated by Django 4.1.1 on 2022-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('img', models.ImageField(default='null', upload_to='guias', verbose_name='Portada')),
                ('img1', models.ImageField(default='null', upload_to='guias', verbose_name='Kanto')),
                ('img2', models.ImageField(default='null', upload_to='guias', verbose_name='Hoenn')),
                ('img3', models.ImageField(default='null', upload_to='guias', verbose_name='Teselia')),
                ('img4', models.ImageField(default='null', upload_to='guias', verbose_name='Sinnoh')),
                ('video', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
        ),
    ]
