# Generated by Django 4.1.1 on 2022-11-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descarga'),
        ),
    ]
