# Generated by Django 4.1.1 on 2022-11-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0002_guia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
