# Generated by Django 4.1.1 on 2022-11-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0003_alter_guia_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='link',
        ),
    ]
