# Generated by Django 4.1.1 on 2022-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nombre')),
                ('time', models.IntegerField(verbose_name='Tiempo')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripción')),
                ('seed1', models.CharField(max_length=255, verbose_name='Semilla 1')),
                ('seed2', models.CharField(max_length=255, verbose_name='Semilla 2')),
                ('seed3', models.CharField(default='', max_length=255, verbose_name='Semilla 3')),
            ],
            options={
                'verbose_name': 'Baya',
                'verbose_name_plural': 'Bayas',
            },
        ),
    ]
