# Generated by Django 4.1.1 on 2022-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baya',
            name='imagen',
            field=models.ImageField(default='null', upload_to='berrys', verbose_name='Imagen'),
        ),
    ]
